
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asif
 */
public class Main_Frame extends javax.swing.JFrame {
    Basic_Functions bf = new Basic_Functions();
    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
        //Setting screen size full
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize( xsize, ysize );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        header_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button_panel = new javax.swing.JPanel();
        Welcome_Admin_Btn = new javax.swing.JButton();
        Customers_Btn = new javax.swing.JButton();
        Reports_Btn = new javax.swing.JButton();
        System_Setup_Btn = new javax.swing.JButton();
        Logout_Btn = new javax.swing.JButton();
        functions_panel = new javax.swing.JPanel();
        welcome_admin_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customers_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        reports_panel = new javax.swing.JPanel();
        system_setup_panel = new javax.swing.JPanel();
        Add_New_Employee_btn = new javax.swing.JButton();
        Update_Employee_Btn = new javax.swing.JButton();
        Delete_Employee_Btn = new javax.swing.JButton();
        Search_Employee_Btn = new javax.swing.JButton();
        system_setup_internal_panel = new javax.swing.JPanel();
        add_new_employee_panel = new javax.swing.JPanel();
        update_employee_panel = new javax.swing.JPanel();
        delete_employee_panel = new javax.swing.JPanel();
        search_employee_panel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(204, 70, 15));
        jSeparator1.setForeground(new java.awt.Color(204, 70, 15));

        header_panel.setBackground(new java.awt.Color(30, 48, 50));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LIMS");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        button_panel.setBackground(new java.awt.Color(30, 48, 50));

        Welcome_Admin_Btn.setBackground(new java.awt.Color(30, 48, 50));
        Welcome_Admin_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Welcome_Admin_Btn.setText("Welcome Admin");
        Welcome_Admin_Btn.setPreferredSize(new java.awt.Dimension(190, 40));
        Welcome_Admin_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Welcome_Admin_BtnActionPerformed(evt);
            }
        });

        Customers_Btn.setBackground(new java.awt.Color(30, 48, 50));
        Customers_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Customers_Btn.setText("Customers");
        Customers_Btn.setPreferredSize(new java.awt.Dimension(190, 40));
        Customers_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customers_BtnActionPerformed(evt);
            }
        });

        Reports_Btn.setBackground(new java.awt.Color(30, 48, 50));
        Reports_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Reports_Btn.setText("Reports");
        Reports_Btn.setPreferredSize(new java.awt.Dimension(190, 40));
        Reports_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reports_BtnActionPerformed(evt);
            }
        });

        System_Setup_Btn.setBackground(new java.awt.Color(30, 48, 50));
        System_Setup_Btn.setForeground(new java.awt.Color(255, 255, 255));
        System_Setup_Btn.setText("System Setup");
        System_Setup_Btn.setPreferredSize(new java.awt.Dimension(190, 40));
        System_Setup_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System_Setup_BtnActionPerformed(evt);
            }
        });

        Logout_Btn.setBackground(new java.awt.Color(30, 48, 50));
        Logout_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Logout_Btn.setText("Log Out");
        Logout_Btn.setPreferredSize(new java.awt.Dimension(190, 40));

        javax.swing.GroupLayout button_panelLayout = new javax.swing.GroupLayout(button_panel);
        button_panel.setLayout(button_panelLayout);
        button_panelLayout.setHorizontalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Welcome_Admin_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Customers_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Reports_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(System_Setup_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logout_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        button_panelLayout.setVerticalGroup(
            button_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_panelLayout.createSequentialGroup()
                .addComponent(Welcome_Admin_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Customers_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Reports_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(System_Setup_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Logout_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        functions_panel.setLayout(new java.awt.CardLayout());

        welcome_admin_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel2.setText("WELCOME TO");

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 48)); // NOI18N
        jLabel3.setText("LIMS");

        javax.swing.GroupLayout welcome_admin_panelLayout = new javax.swing.GroupLayout(welcome_admin_panel);
        welcome_admin_panel.setLayout(welcome_admin_panelLayout);
        welcome_admin_panelLayout.setHorizontalGroup(
            welcome_admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_admin_panelLayout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(welcome_admin_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        welcome_admin_panelLayout.setVerticalGroup(
            welcome_admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_admin_panelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        functions_panel.add(welcome_admin_panel, "card2");

        customers_panel.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Add Customer");

        jButton2.setText("Select Test");

        jButton3.setText("Close");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout customers_panelLayout = new javax.swing.GroupLayout(customers_panel);
        customers_panel.setLayout(customers_panelLayout);
        customers_panelLayout.setHorizontalGroup(
            customers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customers_panelLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customers_panelLayout.setVerticalGroup(
            customers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customers_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        functions_panel.add(customers_panel, "card2");

        javax.swing.GroupLayout reports_panelLayout = new javax.swing.GroupLayout(reports_panel);
        reports_panel.setLayout(reports_panelLayout);
        reports_panelLayout.setHorizontalGroup(
            reports_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        reports_panelLayout.setVerticalGroup(
            reports_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(reports_panel, "card2");

        system_setup_panel.setBackground(new java.awt.Color(255, 255, 255));

        Add_New_Employee_btn.setText("Add New Employe");
        Add_New_Employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_New_Employee_btnActionPerformed(evt);
            }
        });

        Update_Employee_Btn.setText("Update Employee");
        Update_Employee_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Employee_BtnActionPerformed(evt);
            }
        });

        Delete_Employee_Btn.setText("Delete Employee");
        Delete_Employee_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_Employee_BtnActionPerformed(evt);
            }
        });

        Search_Employee_Btn.setText("Search Employee");
        Search_Employee_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_Employee_BtnActionPerformed(evt);
            }
        });

        system_setup_internal_panel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout add_new_employee_panelLayout = new javax.swing.GroupLayout(add_new_employee_panel);
        add_new_employee_panel.setLayout(add_new_employee_panelLayout);
        add_new_employee_panelLayout.setHorizontalGroup(
            add_new_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        add_new_employee_panelLayout.setVerticalGroup(
            add_new_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        system_setup_internal_panel.add(add_new_employee_panel, "card2");

        javax.swing.GroupLayout update_employee_panelLayout = new javax.swing.GroupLayout(update_employee_panel);
        update_employee_panel.setLayout(update_employee_panelLayout);
        update_employee_panelLayout.setHorizontalGroup(
            update_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        update_employee_panelLayout.setVerticalGroup(
            update_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        system_setup_internal_panel.add(update_employee_panel, "card2");

        javax.swing.GroupLayout delete_employee_panelLayout = new javax.swing.GroupLayout(delete_employee_panel);
        delete_employee_panel.setLayout(delete_employee_panelLayout);
        delete_employee_panelLayout.setHorizontalGroup(
            delete_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        delete_employee_panelLayout.setVerticalGroup(
            delete_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        system_setup_internal_panel.add(delete_employee_panel, "card2");

        javax.swing.GroupLayout search_employee_panelLayout = new javax.swing.GroupLayout(search_employee_panel);
        search_employee_panel.setLayout(search_employee_panelLayout);
        search_employee_panelLayout.setHorizontalGroup(
            search_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        search_employee_panelLayout.setVerticalGroup(
            search_employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        system_setup_internal_panel.add(search_employee_panel, "card2");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        system_setup_internal_panel.add(jPanel12, "card2");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        system_setup_internal_panel.add(jPanel13, "card2");

        javax.swing.GroupLayout system_setup_panelLayout = new javax.swing.GroupLayout(system_setup_panel);
        system_setup_panel.setLayout(system_setup_panelLayout);
        system_setup_panelLayout.setHorizontalGroup(
            system_setup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(system_setup_panelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(Add_New_Employee_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Update_Employee_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete_Employee_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_Employee_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(system_setup_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(system_setup_internal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        system_setup_panelLayout.setVerticalGroup(
            system_setup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(system_setup_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(system_setup_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_New_Employee_btn)
                    .addComponent(Update_Employee_Btn)
                    .addComponent(Delete_Employee_Btn)
                    .addComponent(Search_Employee_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(system_setup_internal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        functions_panel.add(system_setup_panel, "card2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(jPanel5, "card2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(jPanel6, "card2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(jPanel7, "card2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(jPanel8, "card2");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(jPanel9, "card2");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        functions_panel.add(jPanel10, "card2");

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addComponent(button_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(functions_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(functions_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Welcome_Admin_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Welcome_Admin_BtnActionPerformed
        bf.Buttoncall(functions_panel, welcome_admin_panel);
    }//GEN-LAST:event_Welcome_Admin_BtnActionPerformed

    private void Customers_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customers_BtnActionPerformed
        bf.Buttoncall(functions_panel, customers_panel);
    }//GEN-LAST:event_Customers_BtnActionPerformed

    private void Reports_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reports_BtnActionPerformed
        bf.Buttoncall(functions_panel, reports_panel);
    }//GEN-LAST:event_Reports_BtnActionPerformed

    private void System_Setup_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_System_Setup_BtnActionPerformed
        bf.Buttoncall(functions_panel, system_setup_panel);
    }//GEN-LAST:event_System_Setup_BtnActionPerformed

    private void Add_New_Employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Employee_btnActionPerformed
        bf.Buttoncall(system_setup_internal_panel, add_new_employee_panel);
    }//GEN-LAST:event_Add_New_Employee_btnActionPerformed

    private void Update_Employee_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Employee_BtnActionPerformed
       bf.Buttoncall(system_setup_internal_panel, update_employee_panel); 
    }//GEN-LAST:event_Update_Employee_BtnActionPerformed

    private void Delete_Employee_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Employee_BtnActionPerformed
        bf.Buttoncall(system_setup_internal_panel, delete_employee_panel); 
    }//GEN-LAST:event_Delete_Employee_BtnActionPerformed

    private void Search_Employee_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Employee_BtnActionPerformed
       bf.Buttoncall(system_setup_internal_panel, search_employee_panel); 
    }//GEN-LAST:event_Search_Employee_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Employee_btn;
    private javax.swing.JButton Customers_Btn;
    private javax.swing.JButton Delete_Employee_Btn;
    private javax.swing.JButton Logout_Btn;
    private javax.swing.JButton Reports_Btn;
    private javax.swing.JButton Search_Employee_Btn;
    private javax.swing.JButton System_Setup_Btn;
    private javax.swing.JButton Update_Employee_Btn;
    private javax.swing.JButton Welcome_Admin_Btn;
    private javax.swing.JPanel add_new_employee_panel;
    private javax.swing.JPanel button_panel;
    private javax.swing.JPanel customers_panel;
    private javax.swing.JPanel delete_employee_panel;
    private javax.swing.JPanel functions_panel;
    private javax.swing.JPanel header_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel reports_panel;
    private javax.swing.JPanel search_employee_panel;
    private javax.swing.JPanel system_setup_internal_panel;
    private javax.swing.JPanel system_setup_panel;
    private javax.swing.JPanel update_employee_panel;
    private javax.swing.JPanel welcome_admin_panel;
    // End of variables declaration//GEN-END:variables
}
